name: "vault-reader"
description: "Read full secret from vault as JSON"
inputs:
  vault_addr:
    description: "Vault address"
    required: true
  vault_path:
    description: "Vault path to secret"
    required: true
  vault_role_id:
    description: "Vault role id"
    required: true
  vault_secret_id:
    description: "Vault secret id"
    required: true
  vault_secret_version:
    description: "Version of secret"
    required: false
    default: ""
  to_base64:
    description: "Convert JSON to BASE64 string"
    required: false
    default: "false"
outputs:
  data:
    description: "Readed json data"
runs:
  using: "node20"
  main: "dist/index.js"
